version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_flora
    command: gunicorn flora_flow.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=flora_flow.settings

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "8081:80"  # Map port 80 in the container to port 8081 on the host
      - "4433:443"
    depends_on:
      - web

volumes:
  media_volume:
